tuning_arena_index: 4
clock_time_hours: 0.25
n_trials: 10
per_era_int_spaces:
  BATTLEROUNDS_LIST: [1, 200]
  BENCHMARK_BATTLE_FREQUENCY_LIST: [0, 50]
  CHAMPION_BATTLE_FREQUENCY_LIST: [0, 50]
  RANDOM_PAIR_BATTLE_FREQUENCY_LIST: [0, 200]
  ARCHIVE_LIST: [0, 10000]
  UNARCHIVE_LIST: [0, 10000]
  CROSSOVERRATE_LIST: [1, 40]
  TRANSPOSITIONRATE_LIST: [1, 40]
  NOTHING_LIST: [0, 40]
  RANDOM_LIST: [0, 20]
  NAB_LIST: [0, 20]
  MINI_MUT_LIST: [0, 20]
  MICRO_MUT_LIST: [0, 20]
  LIBRARY_LIST: [0, 20]
  MAGIC_NUMBER_LIST: [0, 20]
per_era_bool_keys:
  - PREFER_WINNER_LIST
